services:
  app:
    build: .
    container_name: invoiceping
    restart: unless-stopped
    ports:
      - "8077:8077"
    volumes:
      - ./database:/app/database
    environment:
      - APP_ENV=production
